base/urls.py
from django.urls import path
from . import views


app_name = 'base'

urlpatterns = [
    path('', views.home, name='home'),
    path('room/<str:pk>', views.room, name='room'),
    path('create-room/', views.create_room, name='create-room')

]

studybud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True) # dont delete Room if topic del but set value for topic = null
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True) # bigger field / database and form can be empty
    # participants = 
    updated = models.DateTimeField(auto_now=True) # save date every time updated
    created = models.DateTimeField(auto_now_add=True) # save date only first time

    def __str__(self):
        return self.name
    

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE) # when parent Room is del all children Message are del
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True) 
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[0:50] # preview first 50 char of msg
    

base/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Room, Topic, Message



def home(request):
    rooms = Room.objects.all()
    return render(request, 'base/home.html', {'rooms': rooms})

def room(request, pk):
    room = Room.objects.get(id=pk)
    context = {'room': room} # room num return when go to url
    return render(request, 'base/room.html', context)

def create_room(request):
    context = {}
    return render(request, 'base/room_form.html', context)

base/templates/base/home.html
{% extends 'main.html' %}


{% block content%}

<h1>Home template</h1>

<div>

    <a href="{% url base:create-room }">Create Room</a>

    <div>
    <h3>Rooms:</h3>
        {% for room in rooms %}
        <div>
            <span>@{{room.host.username}}</span>
            <a href="{% url 'base:room' room.id %}"> 
                <h4>{{room.id}} - {{room.name}}</h4>
            </a>
            <small>{{room.topic.name}}</small>
            <hr>
        </div>
        {% endfor %}
    </div>


</div>

{% endblock content %}

base/templates/base/room.html
{% extends 'main.html' %}


{% block content%}

<h1>{{room.name}}</h1>

<div>
    <h5>{{room.description}}</h5>
</div>

{% endblock content %}

base/templates/base/room_form.html
{% extends 'main.html' %}

{% block content%}

<h1>{{room.name}}</h1>

<div>
    <!-- method: send data to action: url-->
    <form method="POST" action="">
        {% csrf_token %}
        <!-- send token with request for security -->

        <input type="submit" value="Submit" />

    </form>
</div>

{% endblock content %}

templates/main.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>StudyBud</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- <link rel='stylesheet' type='text/css' media='screen' href='main.css'> -->
</head>

<body>
    {% include 'navbar.html' %}
    
    {% block content %}


    {% endblock %}


</body>

</html>

templates/navbar.html
<a href="/"> <!-- go to home -->
    <h1>LOGO</h1>
</a>

<hr> <!-- line break -->